group = 'com.wanliyunyan.xraycoresdk'
version = '0.3.1'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.1'
    }
}

apply plugin: 'com.android.library'

android {
    namespace = 'com.wanliyunyan.xraycoresdk'
    compileSdk = 35

    defaultConfig {
        minSdk = 21
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_shared'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path '../src/CMakeLists.txt'
        }
    }
}
